# Site settings
title: Ryan Tabora
email: ratabora@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ryan Tabora's rants and ramblings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ratabora.github.io" # the base hostname & protocol for your site
twitter_username: ryantabora
github_username:  ratabora

# Build settings
markdown: kramdown
